name: dealtors_vendor
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.5

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  http: ^0.13.5
  shared_preferences: ^0.5.1+1
  flutter_html: ^0.8.2
  flutter_rating_bar: ^3.2.0+1
  smooth_star_rating: ^1.1.1
  carousel_pro: ^1.0.0
  carousel_slider: ^3.0.0
  modal_progress_hud: ^0.1.3
  retrofit: ^4.0.1
  dio: ^5.0.3
  built_value: ^8.4.4
  json_annotation: ^4.8.0
  loadmore: ^1.0.4
  package_info: ^0.4.3+4
  email_validator: ^1.0.6
  readmore: 2.1.0
  date_format: any
  image_picker: ^0.8.0+4
  url_launcher: ^5.7.10
  connectivity: ^2.0.2
  http_auth: ^0.3.1
  webview_flutter: ^1.0.7
  store_redirect: ^1.0.2
  firebase_core: ^0.8.0-nullsafety.1
  firebase_auth: ^0.21.0-nullsafety.0


#flutter_icons:
  #android: true
 # ios: true
 # image_path: "assets/app_icon.png"

dev_dependencies:
  flutter_launcher_icons: ^0.12.0
  retrofit_generator: ^6.0.0+1
  build_runner: ^2.3.3
  json_serializable: ^6.6.1
  built_value_generator: ^8.4.4

  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/noimage.png
    - assets/success_paymnet.png
    - assets/fail_payment.png
    - assets/blocked_user.jpg
    - assets/home_logo.jpg
    - assets/alert_green.jpg
    - assets/wellcome_image.jpg
    - assets/account_verify.jpg
    - assets/verified_fail.jpg
    - assets/success_alert.jpg
    - assets/my_coupon.png
    - assets/verify_coupon.png
    - assets/no_data.png
    - assets/waiting_for_approvel.png
    - assets/loader.gif
    - assets/whatsapp_icon.png

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  fonts:
    - family: poppins_bold
      fonts:
        - asset: assets/Fonts/poppins/Poppins-Bold.ttf

    - family: poppins_medium
      fonts:
        - asset: assets/Fonts/poppins/Poppins-Medium.ttf

    - family: poppins_regular
      fonts:
        - asset: assets/Fonts/poppins/Poppins-Regular.ttf

    - family: poppins_extrabold
      fonts:
        - asset: assets/Fonts/poppins/Poppins-ExtraBold.ttf

    - family: poppins_medium_italic
      fonts:
        - asset: assets/Fonts/poppins/Poppins-MediumItalic.ttf

    - family: poppins_italic
      fonts:
        - asset: assets/Fonts/poppins/Poppins-Italic.ttf

    - family: poppins_black
      fonts:
        - asset: assets/Fonts/poppins/Poppins-Black.ttf

  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
